name: clocz
base: core22
version: v
summary: A fast, multi-threaded line-of-code counter
description: |
  clocz counts lines of code, comments, and blanks across 60+ programming
  languages. It uses multi-threaded directory scanning for high performance
  and produces a tabular summary sorted by code lines.

grade: stable
confinement: strict

apps:
  clocz:
    command: bin/clocz
    plugs:
      - home
      - removable-media

parts:
  zig:
    plugin: nil
    build-packages:
      - curl
      - xz-utils
    override-build: |
      snap install zig --classic --beta

  clocz:
    after: [zig]
    plugin: nil
    source: .
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/zig:$PATH"
      zig build -Doptimize=ReleaseFast
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp zig-out/bin/clocz $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libc6
